from typing import Protocol

from src.domain.entities.short.short import Short


class IShortRepository(Protocol):
    async def get_shorts(id:str):
        ...
    async def get_shorts_by_user_id(id:str):
        ...
    async def get_shorts_by_movie_id(id:str):
        ...
    async def get_shorts_by_episode_id(id:str):
        ...
    async def get_short_by_self_id(id:str):
        ...
    async def create_short(short:Short):
        ...
    async def delete_short(id:str):
        ...
