from typing import Protocol

from src.presentation.dtos.short_dto import ShortCreateDTO


class IShortService(Protocol):

    async def get_shorts(id_user:str):
        ...
    async def get_shorts_by_user_id(id:str):
        ...
    async def get_shorts_by_movie_id(id:str):
        ...
    async def get_shorts_by_episode_id(id:str):
        ...
    async def get_short_by_self_id(id:str):
        ...
    async def create_short(ShortCreateDTO:ShortCreateDTO):
        ...
    async def delete_short(id:str):
        ...
        